<?php

/**
 * Media - Remove Extra Image Sizes
 *
 * A snippet that allows you to programmatically remove image sizes generated by WordPress, your theme, or some plugins. Great for removing unwanted image sizes that aren't used anywhere and just add more bloat to your server disk space and your database.
 * 
 * Remember to Regenerate Thumbnails after activating this snippet. A great plugin that does this is the reGenerate Thumbnails Advanced.
 */
/**
 * Remove Extra Image Sizes
 * Add to the line:24 the name of the image sizes that you DON'T want to remove, separated by commas
 * and wrapped by ''
 * 
 * @author: Nicholas Zein
 * @link: https://github.com/zeinnicholas/My-Code-Snippets-Collection
 *
 * @version: 	1.0.0
 * @published: 	2020-10-16
 * @updated: 	2020-10-16
 *
 * @params: ! in_array( $size )
 * @examples: 'thumbnail', 'medium', 'medium_large', 'large', '1536x1536', '2048x2048',
 * 'woocommerce_thumbnail', 'woocommerce_single', 'woocommerce_gallery_thumbnail', 
 * 'shop_catalog', 'shop_single', 'shop_thumbnail'
 * 
 * @original_author: https://profiles.wordpress.org/nikschavan/
 * @reference: https://developer.wordpress.org/reference/functions/remove_image_size/#comment-1569
 */
function codesnippets_remove_extra_image_sizes() {
    foreach ( get_intermediate_image_sizes() as $size ) {
        // @array 'thumbnail', 'medium', 'medium_large', 'large', '1536x1536', '2048x2048', 'woocommerce_thumbnail', 'woocommerce_single', 'woocommerce_gallery_thumbnail', 'shop_catalog', 'shop_single', 'shop_thumbnail'
        if ( ! in_array( $size, array( 'thumbnail', 'medium', 'large' ) ) ) {
            remove_image_size( $size );
        }
    }
}
add_action( 'init', 'codesnippets_remove_extra_image_sizes' );
