<?php

/**
 * Media - Add/Update Image Sizes
 *
 * A snippet that allows you to programmatically add or rewrite image sizes generated by WordPress, themes, and plugins. Great for reconfiguring image sizes that do not fit your website requirements (too large, too small, cropping, un-cropping, adding new sizes, etc.).
 * 
 * For default WordPress image sizes, it's recommended that you use the options available in your Dashboard &gt; Settings &gt; Media. But if you want you can still point them or other image sizes to these settings in order to use them to change sizes that you can't remove but want to stop WordPress from generating more files.
 */
/**
 * Add/Update Image Sizes
 * Uncomment (remove the '//' at the beginnig of each line) the sizes you want to resize.
 * 
 * @author: Nicholas Zein
 * @link: https://github.com/zeinnicholas/My-Code-Snippets-Collection
 *
 * @version: 	1.0.0
 * @published: 	2020-10-16
 * @updated: 	2020-10-16
 *
 * @params: array( string $name, int $width, int $height, bool|array $crop = false )
 * @required: $name
 * 
 * @reference: https://developer.wordpress.org/reference/functions/add_image_size/
 */
function codesnippets_add_update_image_sizes() {
    /* thumbnail - Default: 150x150, Crop */
//    add_image_size('thumbnail', get_option( 'thumbnail_size_w' ), get_option( 'thumbnail_size_h' ), get_option( 'thumbnail_crop' ) );
	
    /* medium - Default: 300x300, Uncrop */
//    add_image_size('medium', get_option( 'medium_size_w' ), get_option( 'medium_size_h' ), false );
	
    /* medium_large - Default: 768x0, Uncrop */
//    add_image_size('medium_large', 768, 0, false );
	
    /* large - Default: 1024x1024, Uncrop */
//    add_image_size('large', get_option( 'large_size_w' ), get_option( 'large_size_h' ), false );
	
    /* 1536x1536 - Default: 1536x1536, Crop */
//    add_image_size('1536x1536', 1536, 1536, true );
	
    /* 2048x2048 - Default: 2048x2048, Crop */
//    add_image_size('2048x2048', 2048, 2048, true );
	
	/* Extra sizes for WooCommerce control */
	
    /* woocommerce_thumbnail - Default: 300x300, Crop */
//    add_image_size('woocommerce_thumbnail', 300, 300, false );
	
    /* woocommerce_single - Default: 600x0, Uncrop */
//    add_image_size('woocommerce_single', 600, 0, false );
	
    /* woocommerce_gallery_thumbnail - Default: 100x100, Crop */
//    add_image_size('woocommerce_gallery_thumbnail', 100, 100, true );
	
    /* shop_catalog - Default: 300x300, Crop */
//    add_image_size('shop_catalog', 300, 300, true );
	
    /* shop_single -  Default: 600x0, Uncrop */
//    add_image_size('shop_single', 600, 0, false );
	
    /* shop_thumbnail - Default: 100x100, Crop */
//    add_image_size('shop_thumbnail', 100, 100, true );
	
}
add_action( 'init', 'codesnippets_add_update_image_sizes' );
